// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXMPC9MxTUwRh9-IpH4fsbXB0J5huCXKc',
    appId: '1:367743248268:web:46840ab01028bf20cd58a9',
    messagingSenderId: '367743248268',
    projectId: 'expense-tracker-d468e',
    authDomain: 'expense-tracker-d468e.firebaseapp.com',
    storageBucket: 'expense-tracker-d468e.firebasestorage.app',
    measurementId: 'G-MP41PP1NE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl4dLxu8vQbGhTdGT68P4nLebgmm6c0fs',
    appId: '1:367743248268:android:bc9a5cae74e29618cd58a9',
    messagingSenderId: '367743248268',
    projectId: 'expense-tracker-d468e',
    storageBucket: 'expense-tracker-d468e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvGlncmkJBd4-8HaVSiEwfFOmsTGsWcTY',
    appId: '1:367743248268:ios:2837d6bed792db20cd58a9',
    messagingSenderId: '367743248268',
    projectId: 'expense-tracker-d468e',
    storageBucket: 'expense-tracker-d468e.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTrackerWithAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvGlncmkJBd4-8HaVSiEwfFOmsTGsWcTY',
    appId: '1:367743248268:ios:2837d6bed792db20cd58a9',
    messagingSenderId: '367743248268',
    projectId: 'expense-tracker-d468e',
    storageBucket: 'expense-tracker-d468e.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseTrackerWithAiAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXMPC9MxTUwRh9-IpH4fsbXB0J5huCXKc',
    appId: '1:367743248268:web:0f2d4385abe70254cd58a9',
    messagingSenderId: '367743248268',
    projectId: 'expense-tracker-d468e',
    authDomain: 'expense-tracker-d468e.firebaseapp.com',
    storageBucket: 'expense-tracker-d468e.firebasestorage.app',
    measurementId: 'G-QHJW163LRF',
  );
}
